main: nl.parrotlync.discovjukebox.DiscovJukebox
name: ${artifactId}
version: ${version}
description: ${description}
api-version: 1.15
author: ParrotLync
depend: [MCJukebox, WorldGuard]
commands:
  fun:
    description: Listen to music in the /fun channel
    usage: /fun
  music:
    description: Auto-start music in shows for regions
    usage: /music
permissions:
  discovjukebox.fun:
    default: op
    description: Permission to operate /fun
  discovjukebox.music:
    default: op
    description: Access to the /music commands
